[default]
optimizer = true
optimizer_runs = 20000
# via_ir = true temporarily disable for faster snapshot

gas_reports = [
  "*",
  # "MarginAccount", 
  # "OptionToken", 
  # "MarginAccountGasTester", # expose internal functions for gas report
  # "ChainlinkPricer"
]

[lite]
via_ir = false
optimizer_runs = 200