name: Slither Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLC_VERSION: "v0.8.13"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Run Slither
        uses: crytic/slither-action@main
        continue-on-error: true
        with:
          target: "src/core"
          slither-config: "slither.config.json"

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}