name: Slither Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLC_VERSION: "v0.8.13"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      
      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Install Sol-Selec
        run: pip3 install solc-select

      - name: Install solc 
        run: solc-select install 0.8.13 && solc-select use 0.8.13

      - name: Run Slither
        run: slither src/core --config-file slither.config.json


      # - name: Compile
      #   run: forge build

      # - name: Run Slither
      #   uses: crytic/slither-action@main
      #   with:
      #     sarif: slither.sarif
      #     target: "src/core/"
      #     slither-config: "slither.config.json"

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}